ProjectCode/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path

from core.views import *

urlpatterns = [
    path('', HomePage.as_view(), name='Home_Page'),
    path('category/<int:category_id>/', ThreadListView.as_view(), name='category_page'),
    path('thread/<int:thread_id>/', PostListView.as_view(), name='post_list'),
    path('user-posts/', UserPostsListView.as_view(), name='user_posts'),
    path('create/', CreatePostView.as_view(), name='create_post'),
    path('post_created/', PostCreatedView.as_view(), name='post_created'),
    path('user_threads/', UserThreadsView.as_view(), name='user_threads'),
    path('thread/<int:thread_id>/', ThreadDetailView.as_view(), name='thread_detail'),
    # path('register/', RegisterView.as_view(), name='register'),
    # path('login/', LoginView.as_view(), name='login'),
    # path('logout/', LogoutView.as_view(), name='logout'),
]

core/models.py
from django.db import models
from django.shortcuts import render, redirect


from django.contrib.auth.models import AbstractUser


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Thread(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Post(models.Model):
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    content = models.TextField()

    def __str__(self):
        return f"Post in {self.thread.title}"


class CustomUser(AbstractUser):
    user_name = models.CharField(max_length=100)
    threads = models.ManyToManyField('Thread', related_name='users', blank=True)
    posts = models.ManyToManyField('Post', related_name='users', blank=True)

core/forms.py
from django import forms
from .models import Post, CustomUser, Category, Thread


class PostForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all())  # Added field for selecting category
    thread_title = forms.CharField()  # Added field for entering thread title
    coauthor = forms.ModelChoiceField(queryset=CustomUser.objects.all(), required=False)  # Added optional field for selecting coauthor

    class Meta:
        model = Post
        fields = ['category', 'thread_title', 'content', 'coauthor']  # Included category, thread_title, content, and coauthor fields

    def save(self, commit=True):
        post = super().save(commit=False)
        category = self.cleaned_data['category']
        thread_title = self.cleaned_data['thread_title']
        thread, _ = Thread.objects.get_or_create(title=thread_title, category=category)
        post.thread = thread
        if commit:
            post.save()
            self.save_m2m()
        return post

class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)

core/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import TemplateView, ListView, CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from core.models import *
from core.forms import PostForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import RegistrationForm, LoginForm
import random


class HomePage(TemplateView):
    template_name = 'HTML_Core/HomePage.html'

    def get(self, request):
        context = self.get_context_data()
        return render(request, self.template_name, context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Category.objects.order_by('?')[:6]
        context['categories'] = categories
        return context


class ThreadListView(ListView):
    model = Thread
    template_name = 'HTML_Core/thread_list.html'
    context_object_name = 'threads'

    def get_queryset(self):
        category_id = self.kwargs['category_id']
        category = Category.objects.get(id=category_id)
        return category.thread_set.all()


class PostListView(ListView):
    model = Post
    template_name = 'HTML_Core/post_list.html'
    context_object_name = 'posts'

    def get_queryset(self):
        thread_id = self.kwargs['thread_id']
        thread = Thread.objects.get(id=thread_id)
        return Post.objects.filter(thread=thread)


class UserPostsListView(ListView):
    model = Post
    template_name = 'HTML_Core/user_posts.html'
    context_object_name = 'posts'

    def get_queryset(self):
        user = self.request.user
        return Post.objects.filter(users=user)


class CreatePostView(View):
    def get(self, request):
        form = PostForm()
        return render(request, 'HTML_Core/create_post.html', {'form': form})

    def post(self, request):
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('post_created')
        return render(request, 'HTML_Core/create_post.html', {'form': form})


class PostCreatedView(View):
    def get(self, request):
        return render(request, 'HTML_Core/post_created.html')


# class UserThreadsView(ListView):
#     model = Thread
#     template_name = 'HTML_Core/user_threads.html'
#     context_object_name = 'threads'
#
#     def get_queryset(self):
#         user = self.request.user
#         return Thread.objects.filter(created_by=user)

class UserThreadsView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        threads = Thread.objects.filter(users=user)
        return render(request, 'HTML_Core/user_threads.html', {'threads': threads})

class ThreadDetailView(LoginRequiredMixin, View):
    def get(self, request, thread_id):
        thread = Thread.objects.get(id=thread_id)
        return render(request, 'HTML_Core/thread_detail.html', {'thread': thread})

# class RegisterView(View):
#     def get(self, request):
#         form = RegistrationForm()
#         return render(request, 'HTML_Core/register.html', {'form': form})
#
#     def post(self, request):
#         form = RegistrationForm(request.POST)
#         if form.is_valid():
#             username = form.cleaned_data['username']
#             password = form.cleaned_data['password']
#             user = CustomUser.objects.create_user(username=username, password=password)
#             return redirect('login')
#         return render(request, 'HTML_Core/register.html', {'form': form})
#
# class LoginView(View):
#     def get(self, request):
#         form = LoginForm()
#         return render(request, 'HTML_Core/login.html', {'form': form})
#
#     def post(self, request):
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             username = form.cleaned_data['username']
#             password = form.cleaned_data['password']
#             try:
#                 user = CustomUser.objects.get(username=username)
#                 if user.check_password(password):
#                     request.session['user_id'] = user.id
#                     return redirect('Home_Page')
#                 else:
#                     form.add_error(None, 'Invalid username or password')
#             except CustomUser.DoesNotExist:
#                 form.add_error(None, 'Invalid username or password')
#         return render(request, 'HTML_Core/login.html', {'form': form})
#
# class LogoutView(View):
#     def get(self, request):
#         del request.session['user_id']
#         return redirect('Home_Page')

core/templates/HTML_Core/HomePage.html
{% extends 'HTML_Core/base.html' %}

{% block content%}
    {% for category in categories %}
        <a href="{% url 'category_page' category.id %}">{{ category.name }}</a>
    {% endfor %}
{% endblock %}

core/templates/HTML_Core/base.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link type="text/css" href="{% static 'core/css/styles.css' %}" rel="stylesheet">
    <title>Document</title>
</head>
<body>

<header>
    <nav>
      <ul>
          <li><a href="{% url 'Home_Page' %}">КОМПАНИЯ(HOME)</a></li>
          <li><a href="#">Вход</a>/</li>
          <li><a href="#">Регистрация</a></li>
      </ul>
    </nav>
  </header>

  <div class="sidebar">
    <ul>
      <li><a href="{% url 'user_threads' %}">Мои обсуждения</a></li>
      <li><a href="#">Создать обсуждение</a></li>
      <li><a href="#">Обсуждения</a></li>
    </ul>
  </div>

  <div class="main-content">
    {% block content %}{% endblock %}
  </div>

</body>
</html>

core/templates/HTML_Core/create_post.html
{% extends 'HTML_Core/base.html' %}

{% block content%}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
{% endblock %}

core/templates/HTML_Core/login.html
<h2>Login</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>

core/templates/HTML_Core/post_created.html
{% extends 'HTML_Core/base.html' %}

{% block content%}
    <h1>Done</h1>
{% endblock %}

core/templates/HTML_Core/post_list.html
{% extends 'HTML_Core/base.html' %}

{% block content%}
    {% for post in posts %}
        <p>{{ post.content }}</p>
    {% endfor %}
{% endblock %}

core/templates/HTML_Core/register.html
<h2>Register</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>

core/templates/HTML_Core/thread_detail.html
{% extends 'HTML_Core/base.html' %}

{% block content%}
    <h1>Thread Detail</h1>
    <h2>{{ thread.title }}</h2>
    <p>Category: {{ thread.category }}</p>
    <h3>Posts:</h3>
    <ul>
      {% for post in thread.post_set.all %}
        <li>{{ post.content }}</li>
      {% empty %}
        <li>No posts found.</li>
      {% endfor %}
    </ul>

{% endblock %}

core/templates/HTML_Core/thread_list.html
{% extends 'HTML_Core/base.html' %}

{% block content%}
    {% for thread in threads %}
        <a href="{% url 'post_list' thread.id %}">{{ thread.title }}</a>
    {% endfor %}
{% endblock %}

core/templates/HTML_Core/user_posts.html
{% extends 'HTML_Core/base.html' %}

{% block content%}
    {% for post in posts %}
        <p>{{ post.content }}</p>
    {% endfor %}
{% endblock %}

core/templates/HTML_Core/user_threads.html
{% extends 'HTML_Core/base.html' %}

{% block content%}
    <h1>User Threads</h1>
    <ul>
      {% for thread in threads %}
        <li><a href="{% url 'thread_detail' thread.id %}">{{ thread.title }}</a></li>
      {% empty %}
        <li>No threads found.</li>
      {% endfor %}
    </ul>
{% endblock %}